#! /bin/csh

set dt=1.00
set npts=480
set hcrn=0.05
set lcrn=0.02

fromHelm < $1 > tmp2
window nt=$npts nx=10 nv=1 v0=0 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > tss
window nt=$npts nx=10 nv=1 v0=1 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > tds
window nt=$npts nx=10 nv=1 v0=2 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > xss
window nt=$npts nx=10 nv=1 v0=3 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > xds
window nt=$npts nx=10 nv=1 v0=4 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > xdd
window nt=$npts nx=10 nv=1 v0=5 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > zss
window nt=$npts nx=10 nv=1 v0=6 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > zds
window nt=$npts nx=10 nv=1 v0=7 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > zdd
window nt=$npts nx=10 nv=1 v0=8 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > rex
window nt=$npts nx=10 nv=1 v0=9 < tmp2 > tmp3
bin2sac par=b2s.par npts=$npts < tmp3 > zex

sac << sacend
setbb HCRN $hcrn
getbb HCRN
setbb LCRN $lcrn
getbb LCRN
read tss tds xss xds xdd zss zds zdd rex zex
bp p 2 co %LCRN %HCRN
write over
quit
sacend
